config/routes.rb
 FreshBuilt::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'home#index'
  resources :users do
    resources :photos
    collection do
      post 'search'
    end
    resources :photos
  end

  resources :companies

  resources :workouts do
    member do
      put :confirm_invitation
    end

    collection do
      get :invitations
    end
  end

  post '/login' => 'users#login'
  get '/logout' => 'session#destroy'

  get '/about' => 'home#about'
  get '/company_list' => 'home#company_list'

  get '/checkin' => 'checkins#index'
  post '/checkin' => 'checkins#create'
  post '/record' => 'checkins#record'
  get '/stats' => 'checkins#stats'
  post '/update' => 'checkins#update'

  get '/match' => 'match#index'
  post '/match/filter' => 'match#filter'
  post '/match/search' => 'match#search'

  get '/calendar' => 'calendar#index'

  get '/message' => 'messages#index'
  get '/message/new' => 'messages#new'
  post '/message/create' => 'messages#create'
  post '/message/reply' => 'messages#reply'

end

app/views/shared/_leaderboard.html.erb
<style type="text/css">

.box{
  /*margin: 10px;*/
  margin-top: 40px;
}

.leader{
  /*text-decoration: underline;*/
  display:inline-block;
  margin-bottom: 10px;
  /*padding: 10px;*/
}
.record{
  margin: 5px;
  margin-left: 10px;
  font-size: 12px;
}

.lead{
  text-decoration: none;
  color: white;
}


</style>

<a class="glyph social lead" style='font-size: 20px;'>a  </a>Leaderboard

<div class='box'>

  <a class="glyph general lead" style='font-size: 12px;'>u  </a><span class = 'leader'>Total Workouts</span>
  <% Checkin.frequency[0..2].each do |x,y| %>
    <div class='record'><a class="glyph general lead" style='font-size: 12px;'>c  </a><%= User.find(x).name %>: <%= y %> times</div>
  <% end %>
</div>

<div class='box'>

 <a class="glyph general lead" style='font-size: 12px;'>u  </a> <span class = 'leader'>Weight Loss</span>
  <% Record.frequency[0..2].each do |x,y| %>
    <div class='record'><a class="glyph general lead" style='font-size: 12px;'>c  </a><%= User.find(x).name %></div>
  <% end %>
</div>

app/views/shared/_subnav.html.erb
<style type="text/css">

.sprites{
  padding-top: 50px;
  margin-left: 10px;

}

.sprite_icon{
  float: left;
  color: white;
  margin-left: 10px;

}

</style>




<ul>
  <li><a class="glyph general" style='font-size: 20px;'>f </a><%= link_to 'Check-In', checkin_path, :id => 'chkin' %></li>
  <li><a class="glyph general" style='font-size: 20px;'>A </a><%= link_to "My Profile", user_path(@authenticated_user) %></li>
  <li><a class="glyph general" style='font-size: 20px;'>c </a><%= link_to 'Stats', stats_path, :id => 'stats' %></li>
  <li><a class="glyph general" style='font-size: 20px;'>h </a><%= link_to "Messages #{User.find(@authenticated_user.id).receive.where(read_flag: false).count}", message_path, :id => 'msgs' %></li>
  <li><a class="glyph general" style='font-size: 20px;'>o </a><%= link_to 'Workout Buddies', match_path, :id => 'buds' %></li>
  <li><a class="glyph general" style='font-size: 20px;'>i </a><%= link_to 'Calendar', calendar_path %></li>
  <li><a class="glyph social" style='font-size: 20px;'>t </a><%= link_to 'Photos', user_photos_path(@authenticated_user) %></li>
</ul>



<!-- <a class="glyph general" style='font-size: 20px;'> -->