config/routes.rb
 FreshBuilt::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'home#index'
  resources :users do
    resources :photos
    collection do
      post 'search'
    end
    resources :photos
  end

  resources :companies

  resources :workouts do
    member do
      put :confirm_invitation
    end

    collection do
      get :invitations
    end
  end

  post '/login' => 'users#login'
  get '/logout' => 'session#destroy'

  get '/about' => 'home#about'
  get '/company_list' => 'home#company_list'

  get '/checkin' => 'checkins#index'
  post '/checkin' => 'checkins#create'
  post '/record' => 'checkins#record'
  get '/stats' => 'checkins#stats'
  post '/update' => 'checkins#update'

  get '/match' => 'match#index'
  post '/match/filter' => 'match#filter'
  post '/match/search' => 'match#search'

  get '/calendar' => 'calendar#index'

  get '/message' => 'messages#index'
  get '/message/new' => 'messages#new'
  post '/message/create' => 'messages#create'
  post '/message/reply' => 'messages#reply'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gym Buddy</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :messaging %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

	<header>
    <div class='row'>
    <ul id='gym-bar'>
      <%= image_tag 'logo.png', :style => 'height: 82px; float:left' %><span style='color:#f4f3f1;float: left; margin: 30px -8px;'>ARD BODIES</span>
      <li><%= link_to "LOGOUT", logout_path if session[:user_id] %></li>
      <li><%= link_to 'HOME', checkin_path  if session[:user_id] %></li>
      <li><%= link_to 'ABOUT', about_path %></li>
    </ul>
    </div>
    <div class='clear'></div>
	</header>

  <div class='row h' style='border: 1px solid black; margin-top: 30px; background: #2e2d2c;'>
      <div class='two columns' id='submenu'>
        <%= render 'shared/subnav' if session[:user_id] %>
        <%= yield :match %>
      </div>
      <div id="flash_notice" style="display:none"></div>
      <div class='eight columns h', id="content">
        <%= yield %>
      </div>
      <div class='two columns', id ="leader_board">
        <%= render 'shared/leaderboard' if session[:user_id] %>
      </div>
      <div class='clear'></div>
  </div><!-- row -->


</body>
</html>

app/views/layouts/fancy.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Workout</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <noscript><div>Javascript must be enabled for the correct page display</div></noscript>
    <div class="container" id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gym Buddy</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
  <header>
    <div class='row'>
    <ul id='gym-bar'>
      <%= image_tag 'logo.png', :style => 'height: 82px; float:left' %><span style='color:#f4f3f1;float: left; margin: 30px -8px;'>ARD BODIES</span>
      <li><%= link_to "LOGOUT", logout_path if session[:user_id] %></li>
      <li><%= link_to 'HOME', root_path %></li>
      <li><%= link_to 'ABOUT', about_path %></li>
      <li><%= link_to "CHECKIN", checkin_path if session[:user_id] %></li>
    </ul>
    </div>
    <div class='clear'></div>
  </header>

  <div class='row'>
    <%= yield :background %>
        <%= yield %>
  </div><!-- row -->


</body>
</html>